spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 #????0????
    jedis:
      pool:
        max-active: 8 #?????
        max-wait: 1ms #???????????
        max-idle: 4 #???????????
        min-idle: 0 #???????????
